### ISSUE TITLE
Crash in production in library

### ISSUE THREAD

**Issue by alparp27** [mapbox/mapbox-search-android-examples#25] opened 2021-05-14 21:04 UTC
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapbox.android.telemetry.MapboxTelemetryService$Binder
       at com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider$1.onServiceConnected(MapboxTelemetryInitProvider.java:38)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by DzmitryFomchyn** [comment] 2021-05-17 07:46
Could you please share more context, code examples, steps to get this crash?

**Comment by alparp27** [comment] 2021-05-19 16:47
1. Code examples: I have tried many many things but I cant reproduce the issue.  I have noticed that app crashes 98% when it is in background. (ie. activity is not initialized)
2. Code examples: same as above
3.Search SDK version you are using: v1.0.0-beta.12 from https://docs.mapbox.com/android/search/guides/
4. Android SDK version: all crashes have happened on android 11
5. Device model: they are equally distributed over various devices, affecting samsung, oneplus, pixel, motorola

**Comment by alparp27** [comment] 2021-05-19 16:49
This is my top priority right now, I am sorry email was buried, but please let me know if I can provide any more information.  Reach out to me alpap@everlance.com/alparp27@gmail.com or feel free to call me.  I am ready to jump on phone call/slack call/debug session

**Comment by alparp27** [comment] 2021-05-19 16:51
They look very similar to :
https://github.com/mapbox/mapbox-events-android/issues/207
https://github.com/mapbox/mapbox-gl-native/issues/12460

Please let me know if it is possible to work around it for now.

**Comment by alparp27** [comment] 2021-05-21 02:18
Can we have estimate on this, please?

**Comment by friendoye** [comment] 2021-05-21 16:07
@alparp27 👋 

We haven't identified what is the root cause of the problem yet, but we're working on it. Right now I can say that this problem most certainly relates to our events library and their team is informed. You can track status update via [this issue](https://github.com/mapbox/mapbox-events-android/issues/530).

If you could provide sample app or steps to reproduce this problem, we'd appreciate it!

**Comment by alparp27** [comment] 2021-05-21 16:22
@tarigo is it possible to work around the issue for now?  Passing configuration such that the crashing module is not initialized.  Initializing in activity so that when app is in background which is when crash occurs, initiaizarion is not called and perhaps crash does not happen?

**Comment by tarigo** [comment] 2021-05-21 16:51
> @tarigo is it possible to work around the issue for now? Passing configuration such that the crashing module is not initialized. Initializing in activity so that when app is in background which is when crash occurs, initiaizarion is not called and perhaps crash does not happen?

**Comment by tarigo** [comment] 2021-05-21 17:12
> @tarigo is it possible to work around the issue for now? Passing configuration such that the crashing module is not initialized. Initializing in activity so that when app is in background which is when crash occurs, initiaizarion is not called and perhaps crash does not happen?

I have sent you an email, it would be great if you share the problematic `apk`.

**Comment by alparp27** [comment] 2021-05-21 18:30
https://play.google.com/store/apps/details?id=com.everlance&hl=en_US&gl=US

**Comment by alparp27** [comment] 2021-05-21 19:00
I am not sure if this helps you, but there is another crash in same version but only affected two users out of thousands : https://github.com/mapbox/mapbox-search-android-examples/issues/27

**Comment by DzmitryFomchyn** [comment] 2021-05-25 09:42
@alparp27 
`Search SDK v1.0.0-beta.14` has been released https://github.com/mapbox/mapbox-search-android-examples/releases/tag/v1.0.0-beta.14.

It includes an updated transitive dependency with a [fix](https://github.com/mapbox/mapbox-events-android/pull/531) for this crash.

Looking forward to your feedback!

**Comment by DzmitryFomchyn** [comment] 2021-06-09 14:38
I'm closing this issue, feel free to reopen it or cut a new one if you see this crash again.

**Closed by DzmitryFomchyn** 2021-06-09 14:38 UTC

**Comment by alparp27** [comment] 2021-06-09 21:19
Thanks, so far i have not seen this crash in release, so should be fixed.
