### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by alparp27** [mapbox/mapbox-search-android-examples#43] opened 2021-09-28 16:36 UTC
## Environment

- Android OS version: OS 11
- Devices affected:RED MAGIC 5G (per crashlytics)
- Search SDK Version: 1.0.0-beta.16
- Included in project Maps SDK, Nav SDK versions if available:N/A

## Observed behavior and steps: Unknown steps

Fatal Exception: java.lang.RuntimeException
Unable to create application com.everlance.EverlanceApplication: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a223, callingPackage: com.everlance
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7625)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)
Caused by java.lang.IllegalStateException
Maximum limit of concurrent alarms 500 reached for uid: u0a223, callingPackage: com.everlance
android.os.Parcel.createExceptionOrNull (Parcel.java:2381)
android.app.AlarmManager.setInexactRepeating (AlarmManager.java:797)
com.mapbox.android.telemetry.AlarmSchedulerFlusher.schedule (AlarmSchedulerFlusher.java:43)
com.mapbox.android.telemetry.MapboxTelemetry.startAlarm (MapboxTelemetry.java:401)
com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry (MapboxTelemetry.java:393)
com.mapbox.android.telemetry.MapboxTelemetry.enable (MapboxTelemetry.java:133)
com.mapbox.search.analytics.TelemetryService.<init> (TelemetryService.kt:66)
com.mapbox.search.analytics.TelemetryService.<init> (TelemetryService.kt:63)
com.mapbox.search.MapboxSearchSdk.initializeInternal$mapbox_search_android_release (MapboxSearchSdk.kt:154)
com.mapbox.search.MapboxSearchSdk.initializeInternal$mapbox_search_android_release$default (MapboxSearchSdk.kt:143)
com.mapbox.search.MapboxSearchSdk.initialize (MapboxSearchSdk.kt:118)
com.mapbox.search.MapboxSearchSdk.initialize$default (MapboxSearchSdk.kt:116)
com.mapbox.search.MapboxSearchSdk.initialize (Unknown Source:9)
com.everlance.EverlanceApplication.onCreate (EverlanceApplication.java:131)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1200)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)
Caused by android.os.RemoteException
Remote stack trace: at com.android.server.AlarmManagerService.setImpl(AlarmManagerService.java:1883) at com.android.server.AlarmManagerService$5.set(AlarmManagerService.java:2240) at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:168) at android.os.Binder.execTransactInternal(Binder.java:1175) at android.os.Binder.execTransact(Binder.java:1137)

**Comment by DzmitryFomchyn** [comment] 2021-09-29 12:59
Hey @alparp27,
This is a known bug and, unfortunately, it hasn't been fixed yet. I'll close this issue as duplicate and will try to force progress on solving the root cause https://github.com/mapbox/mapbox-events-android/issues/533

Closing as duplicate https://github.com/mapbox/mapbox-search-android-examples/issues/27

**Closed by DzmitryFomchyn** 2021-09-29 12:59 UTC
Labels: bug
